# Generated by Django 2.0.7 on 2018-08-01 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cefr_level', models.CharField(max_length=2)),
                ('descripion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric', models.CharField(max_length=250)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('answer', models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3')], max_length=1)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SkillSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_system', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='multiplechoiceitem',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.SkillSystem'),
        ),
        migrations.AddField(
            model_name='multiplechoiceitem',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.CEFRLevel'),
        ),
    ]
