# Generated by Django 2.0.7 on 2018-08-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillsystem',
            old_name='skill_system',
            new_name='name',
        ),
        migrations.AddField(
            model_name='skillsystem',
            name='skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillsystem',
            name='system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cefrlevel',
            name='descripion',
            field=models.CharField(max_length=1000),
        ),
    ]
