# Generated by Django 2.0.7 on 2018-09-09 08:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0003_shorttextitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTextItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric', models.CharField(max_length=400)),
                ('word_limit', models.IntegerField(default=250, validators=[django.core.validators.MaxValueValidator(2500), django.core.validators.MinValueValidator(10)])),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.SkillSystem')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.CEFRLevel')),
            ],
        ),
    ]
